Repository prgrms-web-devcourse-final-project/WEB2_3_BlockB_BE, pull requests merged in 2025-03, with the labels that each got.

#52 Feature/#45 news test
  src/main/java/com/example/earthtalk/domain/news/dto/response/NewsDetailResponse.java
  src/main/java/com/example/earthtalk/domain/news/service/NewsDataService.java
  src/main/java/com/example/earthtalk/domain/news/service/NewsService.java
  src/main/java/com/example/earthtalk/global/exception/ErrorCode.java
  src/test/java/com/example/earthtalk/domain/news/service/NewsDataServiceTest.java
  src/test/java/com/example/earthtalk/domain/news/service/NewsFilterTest.java
  src/test/resources/application-test.yml
Labels: ✨feature

#51 Feature/#40 feat redis, ws refactor
  .gitignore
  build.gradle
  src/main/java/com/example/earthtalk/config/RedisConfig.java
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketAuthChannelInterceptor.java
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
  src/main/java/com/example/earthtalk/domain/debate/config/WebSocketConfig.java
  src/main/java/com/example/earthtalk/domain/debate/controller/ChatController.java
  src/main/java/com/example/earthtalk/domain/debate/controller/RealTimeUpdateController.java
  src/main/java/com/example/earthtalk/domain/debate/dto/CreateDebateRoomRequest.java
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateMessage.java
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateMetaDataResponse.java
  src/main/java/com/example/earthtalk/domain/debate/dto/RoomStatusUpdate.java
  src/main/java/com/example/earthtalk/domain/debate/entity/Debate.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateMetaDataService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
  src/main/java/com/example/earthtalk/domain/debate/service/ObserverUserService.java
  src/main/java/com/example/earthtalk/domain/debate/store/DebateRoomStore.java
  src/main/java/com/example/earthtalk/domain/debate/store/DebateUserStore.java
  src/main/java/com/example/earthtalk/domain/debate/store/ObserverRoomStore.java
  src/main/java/com/example/earthtalk/global/exception/ErrorCode.java
  src/main/java/com/example/earthtalk/global/exception/SaveFailedException.java
  src/main/resources/application-dev.yml
  src/test/java/com/example/earthtalk/domain/debate/service/ChatRoomServiceTest.java
  src/test/java/com/example/earthtalk/domain/debate/service/DebateRoomServiceTest.java
  src/test/java/com/example/earthtalk/domain/debate/store/DebateRoomStoreTest.java
  src/test/resources/application-test.yml
Labels: ✨feature

#58 fix: 알림 및 신고 기능 에러 수정
  src/main/java/com/example/earthtalk/config/RedisConfig.java
  src/main/java/com/example/earthtalk/domain/notification/service/FcmTokenService.java
  src/main/java/com/example/earthtalk/domain/notification/service/FirebaseService.java
  src/main/java/com/example/earthtalk/domain/notification/service/NotificationService.java
  src/main/java/com/example/earthtalk/domain/report/dto/request/InsertReportRequest.java
Labels: 🐞bug

#53 feat: 로그인 로직 변경
  src/main/java/com/example/earthtalk/config/FirebaseConfig.java
  src/main/java/com/example/earthtalk/config/OAuth2ClientConfig.java
  src/main/java/com/example/earthtalk/config/SecurityConfig.java
  src/main/java/com/example/earthtalk/controller/AuthController.java
  src/main/java/com/example/earthtalk/controller/OAuth2Controller.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/OAuthAttributes.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/request/SocialAccessTokenRequest.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/TokenResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/accessToken/GoogleAccessTokenResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/accessToken/KakaoAccessTokenResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/accessToken/NaverAccessTokenResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/resource/GoogleResourceResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/resource/KakaoResourceResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/resource/NaverResourceResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/resource/OAuth2UserResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/example/earthtalk/domain/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/example/earthtalk/domain/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/example/earthtalk/domain/oauth/service/OAuth2Service.java
  src/main/java/com/example/earthtalk/domain/oauth/util/GoogleClient.java
  src/main/java/com/example/earthtalk/domain/oauth/util/KakaoClient.java
  src/main/java/com/example/earthtalk/domain/oauth/util/NaverClient.java
  src/main/java/com/example/earthtalk/domain/oauth/util/OAuthClient.java
  src/main/java/com/example/earthtalk/domain/report/entity/Report.java
  src/main/java/com/example/earthtalk/global/exception/ErrorCode.java
  src/main/java/com/example/earthtalk/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/earthtalk/global/security/util/JwtTokenProvider.java
  src/main/resources/application-dev.yml
Labels: ✨feature

#62 fix: redis 관련 설정 파일 수정
  src/main/java/com/example/earthtalk/config/RedisConfig.java
  src/main/resources/application-dev.yml
Labels: 🐞bug

#66 feat: 문제가 일어나는 곳에 스택트레이스 로그 추가
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug

#74 Fix/#73 redis created fix
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateRoomRedisDto.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/store/DebateRoomStore.java
Labels: 🐞bug

#72 feat: 토큰 및 알림 관련 기능 구현 및 신고 에러 해결
  src/main/java/com/example/earthtalk/controller/NotificationController.java
  src/main/java/com/example/earthtalk/domain/notification/dto/request/CheckTokenRequest.java
  src/main/java/com/example/earthtalk/domain/notification/dto/response/NotificationListResponse.java
  src/main/java/com/example/earthtalk/domain/notification/service/FcmTokenService.java
  src/main/java/com/example/earthtalk/domain/notification/service/NotificationService.java
  src/main/java/com/example/earthtalk/domain/report/dto/response/ReportDetailResponse.java
  src/main/java/com/example/earthtalk/domain/report/dto/response/ReportListResponse.java
  src/main/java/com/example/earthtalk/domain/report/entity/Report.java
Labels: 🐞bug, ✨feature

#76 feat: debate에 cachedTime column추가 해당 시간을 기준으로 Redis에서 역순 정렬해올 수 있도록 변경
  src/main/java/com/example/earthtalk/domain/debate/dto/CreateDebateRoomRequest.java
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateRoomRedisDto.java
  src/main/java/com/example/earthtalk/domain/debate/entity/Debate.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/store/DebateRoomStore.java
Labels: 🐞bug

#78 fix: LocalDateTime을 제대로 들어갈 수 있게끔 수정
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateRoomRedisDto.java
Labels: 🐞bug

#83 fix: socketJs는 wildcard를 허용하지 않아 변경
  src/main/java/com/example/earthtalk/domain/debate/config/WebSocketConfig.java
Labels: 🐞bug

#86 토큰 조회 API 반환 값 추가
  src/main/java/com/example/earthtalk/controller/NotificationController.java
  src/main/java/com/example/earthtalk/domain/notification/dto/request/SaveTokenRequest.java
  src/main/java/com/example/earthtalk/domain/notification/dto/response/CheckTokenResponse.java
  src/main/java/com/example/earthtalk/domain/notification/service/FcmTokenService.java
  src/main/java/com/example/earthtalk/domain/notification/service/NotificationService.java
Labels: ✨feature

#92 fix: 알림 읽음 기능 수정
  src/main/java/com/example/earthtalk/domain/notification/service/NotificationService.java
  src/main/java/com/example/earthtalk/domain/report/service/ReportService.java
  src/main/java/com/example/earthtalk/domain/user/service/UserService.java
Labels: 🐞bug

#94 refactor: 배포환경 크롤링 설정 수정
  Dockerfile
  src/main/java/com/example/earthtalk/domain/news/service/NewsService.java
Labels: 🔨refactor, 🌏environment

#96 fix: API 오류 수정 및 프로젝트 시간대 지정
  src/main/java/com/example/earthtalk/EarthTalkApplication.java
  src/main/java/com/example/earthtalk/domain/notification/service/NotificationService.java
  src/main/java/com/example/earthtalk/domain/report/service/ReportService.java
Labels: 🐞bug

#98 fix: debate.getNews가 null 허용이기 때문에 null 처리를 해줌으로써 빌드 에러 핸들링
  src/main/java/com/example/earthtalk/domain/debate/controller/DebateRoomController.java
Labels: 🐞bug

#101 feat: 알림 관련 기능 추가 및 에러 핸들링용 로그 추가
  src/main/java/com/example/earthtalk/controller/AdminController.java
  src/main/java/com/example/earthtalk/controller/NotificationController.java
  src/main/java/com/example/earthtalk/domain/notification/repository/NotificationRepository.java
  src/main/java/com/example/earthtalk/domain/notification/service/NotificationService.java
  src/main/java/com/example/earthtalk/domain/report/entity/Report.java
  src/main/java/com/example/earthtalk/domain/report/service/ReportService.java
Labels: ✨feature

#105 fix: 토큰 관련 로그 추가 및 알림 조회 메서드 수정
  src/main/java/com/example/earthtalk/config/FirebaseConfig.java
  src/main/java/com/example/earthtalk/controller/NotificationController.java
  src/main/java/com/example/earthtalk/domain/notification/repository/NotificationRepository.java
  src/main/java/com/example/earthtalk/domain/notification/service/FirebaseService.java
  src/main/java/com/example/earthtalk/domain/notification/service/NotificationService.java
  src/main/java/com/example/earthtalk/domain/report/service/ReportService.java
Labels: 🔨refactor

#108 test: ws 에러 핸들링하기 위해 messageMapping 경로 변경
  src/main/java/com/example/earthtalk/domain/debate/controller/ChatController.java
Labels: 🔨refactor

#112 refactor: RoomIdInterceptor에 로깅하여 실제로 roomId 를 가져오는지 확인
  src/main/java/com/example/earthtalk/domain/debate/component/RoomIdInterceptor.java
  src/main/java/com/example/earthtalk/domain/debate/controller/DebateRoomController.java
  src/main/java/com/example/earthtalk/domain/debate/repository/DebateRepository.java
Labels: 🔨refactor

#114 fix: ws에서 jwt 제거
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketAuthChannelInterceptor.java
  src/main/java/com/example/earthtalk/domain/debate/config/WebSocketConfig.java
Labels: 🐞bug, 🔨refactor

#116 feat: DebateMessageStore concurrentHashMap에 값이 제대로 들어가는지 로깅
  src/main/java/com/example/earthtalk/domain/debate/controller/ChatController.java
  src/main/java/com/example/earthtalk/domain/debate/store/DebateMessageStore.java
Labels: ✨feature, 🔨refactor

#118 Fix/#117 fix variables
  src/main/java/com/example/earthtalk/domain/debate/controller/ChatController.java
  src/main/java/com/example/earthtalk/domain/debate/controller/DebateRoomController.java
Labels: 🐞bug, 🔨refactor

#120 refactor: 알림 조회 기능 API 수정
  src/main/java/com/example/earthtalk/controller/NotificationController.java
  src/main/java/com/example/earthtalk/domain/notification/repository/NotificationRepository.java
  src/main/java/com/example/earthtalk/domain/notification/service/NotificationService.java
  src/main/java/com/example/earthtalk/domain/user/service/UserService.java
Labels: 🔨refactor

#111 Feature/#109 토론 도중 발언 턴 교체 기능 구현
  src/main/java/com/example/earthtalk/domain/debate/service/DebateManagementService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTurnManagementService.java
Labels: ✨feature

#124 feat: redisconfig 수정
  src/main/java/com/example/earthtalk/config/RedisConfig.java
  src/main/java/com/example/earthtalk/domain/debate/controller/DebateRoomController.java
  src/main/java/com/example/earthtalk/domain/debate/repository/DebateRepository.java
Labels: ✨feature, 🔨refactor

#125 [feat] 정지된 사용자 로그인 예외처리 구현
  src/main/java/com/example/earthtalk/controller/OAuth2Controller.java
  src/main/java/com/example/earthtalk/domain/oauth/service/OAuth2Service.java
  src/main/java/com/example/earthtalk/domain/user/entity/Role.java
  src/main/java/com/example/earthtalk/domain/user/entity/User.java
  src/main/java/com/example/earthtalk/global/exception/ErrorCode.java
  src/main/java/com/example/earthtalk/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/earthtalk/global/exception/UserLockedException.java
Labels: ✨feature, 🔨refactor

#128 fix: redisDto에서 news가 null 일 때 예외 처리 추가
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateRoomRedisDto.java
Labels: 🐞bug

#132 fix: build.gradle 설정 변경
  build.gradle
Labels: 🐞bug

#137 fix: fetchType Lazy error 해결을 위해 명시적으로 초기화
  src/main/java/com/example/earthtalk/domain/debate/dto/CreateDebateRoomRequest.java
  src/test/java/com/example/earthtalk/domain/debate/controller/DebateRoomControllerTest.java
Labels: 🐞bug

#139 fix: fetch type Lazy 문제를 해결하기 위해 news를 제거한 dto, DebateMetaDateRespons…
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateMetaDataResponse.java
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateMetaDataRoomResponse.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateMetaDataService.java
Labels: ✨feature

#145 fix: 신고 복구된 사용자 역할 변경
  src/main/java/com/example/earthtalk/domain/oauth/service/OAuth2Service.java
  src/main/java/com/example/earthtalk/domain/user/entity/User.java
  src/main/resources/application-dev.yml
Labels: 🐞bug

#147 feat: 알림 조회 시 읽지 않은 알림의 개수도 반환
  src/main/java/com/example/earthtalk/controller/NotificationController.java
  src/main/java/com/example/earthtalk/domain/notification/dto/response/NotificationListResponseWithUnreadCount.java
  src/main/java/com/example/earthtalk/domain/notification/repository/NotificationRepository.java
  src/main/java/com/example/earthtalk/domain/notification/service/NotificationService.java
Labels: ✨feature

#149 feat: 소셜로그인 프로필 이미지 리사이징후 저장
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/resource/GoogleResourceResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/resource/KakaoResourceResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/service/OAuth2Service.java
  src/main/java/com/example/earthtalk/domain/user/entity/User.java
Labels: ✨feature

#150 Feat/#148 auto victory msg redisson lock
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateMessage.java
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateResultMessage.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateChatManagementService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
Labels: ✨feature

#152 feat: 사용자 권한 수정 API 구현
  src/main/java/com/example/earthtalk/controller/AdminController.java
  src/main/java/com/example/earthtalk/domain/user/service/UserService.java
Labels: ✨feature

#154 Feat/#153 debate
  src/main/java/com/example/earthtalk/domain/debate/controller/DebateRoomController.java
  src/main/java/com/example/earthtalk/domain/debate/repository/DebateRepository.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: ✨feature

#159 fix: roomlist오탈자 수정
  src/main/java/com/example/earthtalk/domain/debate/config/WebSocketConfig.java
Labels: 🐞bug

#161 feat: query param에 필터링 기능 추가
  src/main/java/com/example/earthtalk/domain/debate/component/QueryHandshakeInterceptor.java
  src/main/java/com/example/earthtalk/domain/debate/config/WebSocketConfig.java
  src/main/java/com/example/earthtalk/domain/debate/controller/FilteredUpdateController.java
Labels: ✨feature

#157 refactor: 토론방 상세 정보 조회에 유저 정보 추가
  src/main/java/com/example/earthtalk/EarthTalkApplication.java
  src/main/java/com/example/earthtalk/controller/UserController.java
  src/main/java/com/example/earthtalk/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/example/earthtalk/domain/user/service/UserService.java
Labels: 🔨refactor

#164 fix: UserDebateRoomInfoResponse push 안함 수정
  src/main/java/com/example/earthtalk/domain/user/dto/response/UserDebateRoomInfoResponse.java
Labels: 🐞bug

#135 fix: 턴 스레드 발생/종료 시점 수정
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
  src/main/java/com/example/earthtalk/domain/debate/controller/DebateRoomController.java
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateResultMessage.java
  src/main/java/com/example/earthtalk/domain/debate/dto/VoteRequest.java
  src/main/java/com/example/earthtalk/domain/debate/entity/EventType.java
  src/main/java/com/example/earthtalk/domain/debate/entity/RoomType.java
  src/main/java/com/example/earthtalk/domain/debate/entity/VoteStatus.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateManagementService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTimerService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTurnManagementService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
  src/main/java/com/example/earthtalk/domain/debate/store/VoteStore.java
  src/main/java/com/example/earthtalk/global/exception/ErrorCode.java
Labels: 🔨refactor

#163 feat: 10분 동안 커넥션이 없는 세션 자동 종료 기능 추가
  src/main/java/com/example/earthtalk/domain/debate/component/SessionRegistry.java
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketIdleSessionMonitor.java
  src/main/java/com/example/earthtalk/domain/debate/controller/ChatController.java
  src/main/java/com/example/earthtalk/domain/debate/controller/FilteredUpdateController.java
  src/main/java/com/example/earthtalk/domain/debate/controller/RealTimeUpdateController.java
  src/main/java/com/example/earthtalk/domain/debate/entity/Debate.java
  src/main/java/com/example/earthtalk/global/exception/ErrorCode.java
Labels: ✨feature

#168 Feat/#167 thread pool config
  src/main/java/com/example/earthtalk/config/ThreadPoolConfig.java
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
Labels: ✨feature

#170 fix: 중복 변수 제거
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
Labels: 🐞bug

#172 fix: 로그를 더 자세하게 보기 위해 log.debug를 info로 변경
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
Labels: 🐞bug

#174 fix: subscribeEvent로 기능 분리
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
Labels: 🐞bug

#176 fix: header에 있는 내용을 제대로 추출해서 가져올 수 있게끔 변경
  src/main/java/com/example/earthtalk/domain/debate/component/RoomIdInterceptor.java
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
Labels: 🐞bug

#178 fix: stomp 헤더에 나온 값을 저장하여 추출할 수 있는 메서드로 변경
  src/main/java/com/example/earthtalk/domain/debate/component/RoomIdInterceptor.java
  src/main/java/com/example/earthtalk/domain/debate/component/StompConnectInterceptor.java
  src/main/java/com/example/earthtalk/domain/debate/config/WebSocketConfig.java
Labels: 🐞bug

#180 fix: handshake 과정에서 null값에 대한 허용으로 변경
  src/main/java/com/example/earthtalk/domain/debate/component/StompConnectInterceptor.java
Labels: 🐞bug

#182 feat: 입장 메시지 연동
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
Labels: ✨feature

#184 feat: pro와 con users의 명수가 최대일 때 error를 내보내도록 수정
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
  src/main/java/com/example/earthtalk/domain/debate/store/DebateUserStore.java
Labels: ✨feature

#186 feat: 인원 초과 입장 이벤트 발생 시 에러 메시지 안내
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
Labels: ✨feature

#188 feat: 추가로 입장한 username을 제공
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
Labels: ✨feature

#189 Feature/#109 debate switch turn
  src/main/java/com/example/earthtalk/domain/debate/repository/DebateRepository.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateManagementService.java
Labels: ✨feature

#190 fix: 영속성 버그 수정
  src/main/java/com/example/earthtalk/domain/debate/service/DebateManagementService.java
Labels: 🐞bug

#191 fix: 소켓 메시지 안날아가던 오류 수정..!
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTimerService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTurnManagementService.java
Labels: 🐞bug

#193 fix: uuid를 추가하여 정렬을 제대로 할 수 있도록 변경
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateMetaDataRoomResponse.java
Labels: 🐞bug

#196 fix: 값이 잘못 들어간 경우를 추적하기 위해 로그 추가
  src/main/java/com/example/earthtalk/domain/debate/service/DebateMetaDataService.java
Labels: 🐞bug

#197 fix: 스레드 관리 버그 수정
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTimerService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTurnManagementService.java
Labels: 🐞bug

#200 fix: 종료된 토론방 조회 등 API 수정
  src/main/java/com/example/earthtalk/domain/debate/controller/DebateRoomController.java
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateRoomResponse.java
  src/main/java/com/example/earthtalk/domain/debate/dto/ObserverMessage.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🔨refactor

#201 Feat/#199 fix observer
  src/main/java/com/example/earthtalk/domain/debate/service/DebateManagementService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
  src/main/java/com/example/earthtalk/domain/debate/store/DebateUserStore.java
  src/main/java/com/example/earthtalk/domain/debate/store/ObserverRoomStore.java
Labels: 🐞bug, ✨feature

#202 fix: 디버그용 로깅 추가, 크롬드라이버 중첩실행 로직 수정
  src/main/java/com/example/earthtalk/domain/debate/controller/ChatRoomController.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/news/service/NewsService.java
Labels: 🐞bug

#206 feat: message에 imageUrl 추가
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateMessage.java
  src/main/java/com/example/earthtalk/domain/debate/dto/ObserverMessage.java
Labels: ✨feature

#210 fix: default로 0이 들어가는 버그 수정
  src/main/java/com/example/earthtalk/domain/debate/entity/Debate.java
Labels: 🐞bug

#213 토론중 턴 변경 로직 버그 수정
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTurnManagementService.java
  src/main/java/com/example/earthtalk/domain/debate/store/VoteStore.java
Labels: 🐞bug

#214 fix: 투표 버그 수정
  src/main/java/com/example/earthtalk/domain/debate/store/VoteStore.java
Labels: 🐞bug

#215 refactor: 토론시작 대기 시간 수정
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTurnManagementService.java
Labels: 🔨refactor

#217 Feat/#216 set redis to waitroom
  src/main/java/com/example/earthtalk/domain/debate/controller/DebateRoomController.java
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateRoomResponse.java
  src/main/java/com/example/earthtalk/domain/debate/repository/DebateParticipantsRepository.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateChatManagementService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateMetaDataService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
  src/test/java/com/example/earthtalk/domain/debate/service/DebateChatManagementServiceTest.java
Labels: ✨feature

#219 fix: 에러로 인한 자바 문법 수정
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug

#221 fix: 디버깅용 로그 추가
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTimerService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTurnManagementService.java
  src/main/java/com/example/earthtalk/domain/debate/store/VoteStore.java
Labels: 🐞bug

#222 fix: 디버그용 로그 추가
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTimerService.java
Labels: 🐞bug

#225 feat: 에러가 생성되는 곳에 로깅 추기
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
  src/main/java/com/example/earthtalk/domain/debate/dto/ObserverMessage.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/store/DebateUserStore.java
Labels: 🔨refactor

#229 feat: response 구조 변경 및 로깅 강화
  src/main/java/com/example/earthtalk/domain/debate/controller/FilteredUpdateController.java
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateMetaDataResponse.java
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateRoomResponse.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateMetaDataService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/store/DebateRoomStore.java
Labels: 🔨refactor

#232 fix: debug level을 info로 변경
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/store/DebateRoomStore.java
Labels: 🔨refactor

#230 fix: 마이페이지 토론 조회시 UUID로 응답하도록 변경
  src/main/java/com/example/earthtalk/controller/UserController.java
  src/main/java/com/example/earthtalk/domain/user/dto/response/UserDebateDetailsResponse.java
  src/main/java/com/example/earthtalk/domain/user/dto/response/UserDebatesResponse.java
  src/main/java/com/example/earthtalk/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/example/earthtalk/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/example/earthtalk/domain/user/service/UserService.java
Labels: ✨feature

#235 Fix/#234 fix filtered structure
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateRoomRedisDto.java
  src/main/java/com/example/earthtalk/domain/debate/repository/DebateParticipantsRepository.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug, 🔨refactor

#237 feat: 로깅 강화
  src/main/java/com/example/earthtalk/domain/debate/controller/DebateRoomController.java
  src/main/resources/application.yml
Labels: 🔨refactor

#239 fix: json 객체를 바로 받아보고 빈 객체를 확인할 수 있도록 로그 강화
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug, 🔨refactor

#241 fix: Long id로 제공되던 것을 UUID로 변경하여 업데이트
  src/main/java/com/example/earthtalk/domain/debate/dto/WaitRoomResponse.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug, 🔨refactor

#245 feat: logging level 변경
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
Labels: 🐞bug, ✨feature

#247 fix: 너무 자주 호출되는 logging 제거
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug

#249 feat: npe가 발생하지 않고 제대로 로깅되도록 수정
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
Labels: 🐞bug

#251 feat: savechathistory 로깅
  src/main/java/com/example/earthtalk/domain/debate/service/DebateChatManagementService.java
Labels: 🐞bug

#253 feat: chatting이 event를 기준으로 잘못 걸러지는 오류 해결
  src/main/java/com/example/earthtalk/domain/debate/service/DebateChatManagementService.java
Labels: 🐞bug

#257 fix: ObserverChat 저장과정에서 생기는 오류 수정
  src/main/java/com/example/earthtalk/domain/debate/service/ObserverChatManagementService.java
Labels: 🐞bug

#265 fix: redis 삭제 로직 시기 변경
  src/main/java/com/example/earthtalk/domain/debate/config/WebSocketConfig.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateManagementService.java
  src/main/java/com/example/earthtalk/domain/debate/service/ObserverChatManagementService.java
  src/main/java/com/example/earthtalk/domain/debate/store/ObserverRoomStore.java
Labels: 🐞bug

#270 fix: redis에서 데이터 삭제 시점 조정
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
  src/main/java/com/example/earthtalk/domain/debate/service/ObserverChatManagementService.java
  src/main/java/com/example/earthtalk/domain/debate/store/DebateRoomStore.java
Labels: 🐞bug

#274 feat: 승리 패배 분기처리
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
  src/main/java/com/example/earthtalk/domain/debate/entity/EventType.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
  src/main/java/com/example/earthtalk/domain/debate/service/ObserverChatManagementService.java
Labels: 🐞bug

#277 fix: buildResponse method 로직 변경
  src/main/java/com/example/earthtalk/domain/debate/service/DebateMetaDataService.java
Labels: 🐞bug, 🔨refactor

#279 fix: observer가 debate 구독시 분기 처리
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
Labels: 🐞bug

#281 fix: redis의 user 제거 로직 수정
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
Labels: 🐞bug

#283 fix: fetch type lazy 문제를 해결하기 위해 transactional annotation 추가
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
Labels: 🐞bug

#285 fix: 로그 제거
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug

#289 feat: winner 칼럼 추가
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateResultMessage.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
Labels: ✨feature

#290 fix: 턴 시간로직 수정
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTimerService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTurnManagementService.java
Labels: 🐞bug, ✨feature

#297 feat: 로깅 추가
  src/main/java/com/example/earthtalk/domain/debate/controller/DebateRoomController.java
Labels: ✨feature

#306 feat: 에러 메시지 로깅
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
  src/main/java/com/example/earthtalk/domain/debate/store/DebateUserStore.java
Labels: 🐞bug

#308 fix: 배포 오류 수정
  .github/workflows/earthtalk-backend-dev.yml
Labels: 🐞bug

#310 fix: response.add구문 추가하여 제대로 전달될 수 있도록 수정
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug

#312 fix : 패배조건시 debate에서 우선 조회
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug

#315 fix: add clear
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug

#317 fix: 조건 강화
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug

#319 fix: conUser쪽으로 들어오도록 수정
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug

#328 refactor: cors 변경
  src/main/java/com/example/earthtalk/config/SecurityConfig.java
Labels: 🔨refactor, 🌏environment

#331 fix: Transactional annotation을 통해 LazyInitializationException 문제 해결
  src/main/java/com/example/earthtalk/domain/debate/service/DebateMetaDataService.java
Labels: 🐞bug

#333 fix: Hibernate.initialize를 통해 LazyInitializationException 해결 시도
  src/main/java/com/example/earthtalk/domain/debate/service/DebateMetaDataService.java
Labels: 🐞bug

#335 fix: fetch join을 활용하여 문제 해결 시도
  src/main/java/com/example/earthtalk/domain/debate/repository/DebateRepository.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateMetaDataService.java
Labels: 🐞bug

#339 fix: 승리 조건 변경 및 lock을 사용해 에러 핸들링
  src/main/java/com/example/earthtalk/domain/debate/repository/DebateRepository.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
Labels: 🐞bug

#343 fix: lock이 필요한 부분에 @Transactional 추가
  src/main/java/com/example/earthtalk/domain/debate/controller/DebateRoomController.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTimerService.java
  src/main/java/com/example/earthtalk/domain/user/service/UserService.java
Labels: 🐞bug

#345 fix: query-requires-transaction 에러 해결을 위해 public으로 변경
  src/main/java/com/example/earthtalk/domain/debate/service/DebateMetaDataService.java
Labels: 🐞bug

#347 fix: transactional 어노테이션 변경
  src/main/java/com/example/earthtalk/domain/debate/service/DebateManagementService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateMetaDataService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateTimerService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
  src/main/java/com/example/earthtalk/domain/debate/service/ObserverChatManagementService.java
  src/main/java/com/example/earthtalk/domain/debate/service/ObserverUserService.java
Labels: 🐞bug

#352 fix: 동시성 문제 해결을 위해 lock 변경
  src/main/java/com/example/earthtalk/domain/debate/repository/DebateRepository.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateMetaDataService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug

#354 fix: lock 문제 해결 시도
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug

#356 fix: 동시성 이슈 문제 해결 시도
  src/main/java/com/example/earthtalk/domain/debate/service/DebateRoomService.java
Labels: 🐞bug

#358 fix: 동시성 문제 해결 시도
  src/main/java/com/example/earthtalk/domain/debate/service/DebateMetaDataService.java
Labels: 🐞bug

#364 refactor: network 변경
  .github/workflows/earthtalk-backend-dev.yml
Labels: 🔨refactor, 🌏environment

#372 fix: mq에서 채팅을 전송하기 때문에 return값을 void로 변경
  src/main/java/com/example/earthtalk/domain/debate/controller/ChatController.java
Labels: 🐞bug
