Repository prgrms-web-devcourse-final-project/WEB2_3_BlockB_BE, pull requests merged in 2025-02, with the labels that each got.

#12 feat : 관리자 페이지 관련 신고 API 개발(페이지네이션)
  src/main/java/com/example/earthtalk/controller/AdminController.java
  src/main/java/com/example/earthtalk/domain/chat/repository/ObserverChatRepository.java
  src/main/java/com/example/earthtalk/domain/debate/repository/DebateChatRepository.java
  src/main/java/com/example/earthtalk/domain/report/ReportType.java
  src/main/java/com/example/earthtalk/domain/report/ResultType.java
  src/main/java/com/example/earthtalk/domain/report/TargetType.java
  src/main/java/com/example/earthtalk/domain/report/dto/request/InsertReportRequest.java
  src/main/java/com/example/earthtalk/domain/report/dto/request/UpdateReportRequest.java
  src/main/java/com/example/earthtalk/domain/report/dto/response/ReportDetailResponse.java
  src/main/java/com/example/earthtalk/domain/report/dto/response/ReportListResponse.java
  src/main/java/com/example/earthtalk/domain/report/entity/Report.java
  src/main/java/com/example/earthtalk/domain/report/entity/ReportType.java
  src/main/java/com/example/earthtalk/domain/report/entity/ResultType.java
  src/main/java/com/example/earthtalk/domain/report/entity/TargetType.java
  src/main/java/com/example/earthtalk/domain/report/repository/ReportRepository.java
  src/main/java/com/example/earthtalk/domain/report/service/ReportService.java
  src/main/java/com/example/earthtalk/global/exception/ErrorCode.java
Labels: ✨feature

#10 feat : 유저 인기순(팔로워순) 조회 API 개발
  build.gradle
  src/main/java/com/example/earthtalk/config/QuerydslConfig.java
  src/main/java/com/example/earthtalk/controller/UsersController.java
  src/main/java/com/example/earthtalk/domain/user/dto/response/UserInfoResponse.java
  src/main/java/com/example/earthtalk/domain/user/repository/UserRepository.java
  src/main/java/com/example/earthtalk/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/example/earthtalk/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/example/earthtalk/domain/user/service/UserService.java
Labels: ✨feature

#15 feat : 유저 인기순 검색 API 개발
  src/main/java/com/example/earthtalk/domain/user/repository/UserRepository.java
  src/main/java/com/example/earthtalk/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/example/earthtalk/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/example/earthtalk/domain/user/service/UserService.java
Labels: ✨feature

#16 feat: 소셜로그인 기본설정 구현
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/com/example/earthtalk/domain/oauth/dto/CustomOAuth2User.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/OAuthAttributes.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/GoogleResourceResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/KakaoResourceResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/NaverResourceResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/OAuth2UserResponse.java
  src/main/java/com/example/earthtalk/domain/user/entity/SocialType.java
  src/main/java/com/example/earthtalk/domain/user/entity/User.java
  src/main/resources/application.yml
Labels: ✨feature

#20 뉴스 크롤링 및 자동 업데이트 기능 개발
  build.gradle
  src/main/java/com/example/earthtalk/EarthTalkApplication.java
  src/main/java/com/example/earthtalk/controller/NewsController.java
  src/main/java/com/example/earthtalk/domain/news/config/CrawlConfig.java
  src/main/java/com/example/earthtalk/domain/news/config/NewsConfig.java
  src/main/java/com/example/earthtalk/domain/news/entity/News.java
  src/main/java/com/example/earthtalk/domain/news/entity/NewsSite.java
  src/main/java/com/example/earthtalk/domain/news/entity/NewsType.java
  src/main/java/com/example/earthtalk/domain/news/repository/NewsRepository.java
  src/main/java/com/example/earthtalk/domain/news/service/NewsService.java
  src/main/resources/application-news.yml
  src/main/resources/application.yml
Labels: ✨feature

#22 feat: 채팅을 db에 저장하는 로직 추가
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
  src/main/java/com/example/earthtalk/domain/debate/controller/ChatController.java
  src/main/java/com/example/earthtalk/domain/debate/dto/DebateMessage.java
  src/main/java/com/example/earthtalk/domain/debate/dto/ObserverMessage.java
  src/main/java/com/example/earthtalk/domain/debate/dto/SessionInfo.java
  src/main/java/com/example/earthtalk/domain/debate/entity/Debate.java
  src/main/java/com/example/earthtalk/domain/debate/entity/DebateChat.java
  src/main/java/com/example/earthtalk/domain/debate/entity/DebateUser.java
  src/main/java/com/example/earthtalk/domain/debate/entity/FlagType.java
  src/main/java/com/example/earthtalk/domain/debate/repository/DebateChatRepository.java
  src/main/java/com/example/earthtalk/domain/debate/repository/DebateRepository.java
  src/main/java/com/example/earthtalk/domain/debate/repository/DebateUserRepository.java
  src/main/java/com/example/earthtalk/domain/debate/service/ChatRoomService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateChatService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateManagementService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateService.java
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
  src/main/java/com/example/earthtalk/domain/debate/service/ObserverMessageService.java
  src/main/java/com/example/earthtalk/domain/debate/store/ChatMessageStore.java
  src/main/java/com/example/earthtalk/domain/debate/store/ChatRoomStore.java
  src/main/java/com/example/earthtalk/domain/debate/store/DebateUserStore.java
  src/main/java/com/example/earthtalk/domain/user/dto/response/UserInfoResponse.java
  src/main/java/com/example/earthtalk/global/exception/ErrorCode.java
  src/test/java/com/example/earthtalk/domain/debate/component/WebSocketEventListenerTest.java
  src/test/java/com/example/earthtalk/domain/debate/service/DebateChatServiceTest.java
  src/test/java/com/example/earthtalk/domain/debate/service/DebateUserServiceTest.java
  src/test/java/com/example/earthtalk/domain/debate/service/ObserverMessageServiceTest.java
Labels: ✨feature

#24 feat: 알림 기능 구현 및 가이드라인 작성
  .gitignore
  build.gradle
  src/main/java/com/example/earthtalk/config/FirebaseConfig.java
  src/main/java/com/example/earthtalk/controller/AdminController.java
  src/main/java/com/example/earthtalk/controller/NotificationController.java
  src/main/java/com/example/earthtalk/domain/notification/dto/request/SaveNotificationRequest.java
  src/main/java/com/example/earthtalk/domain/notification/dto/request/SaveTokenRequest.java
  src/main/java/com/example/earthtalk/domain/notification/dto/request/SendNotificationRequest.java
  src/main/java/com/example/earthtalk/domain/notification/dto/response/NotificationListResponse.java
  src/main/java/com/example/earthtalk/domain/notification/entity/Notification.java
  src/main/java/com/example/earthtalk/domain/notification/entity/NotificationType.java
  src/main/java/com/example/earthtalk/domain/notification/entity/StatusType.java
  src/main/java/com/example/earthtalk/domain/notification/repository/NotificationRepository.java
  src/main/java/com/example/earthtalk/domain/notification/service/FirebaseService.java
  src/main/java/com/example/earthtalk/domain/notification/service/NotificationService.java
  src/main/java/com/example/earthtalk/domain/report/dto/request/InsertReportRequest.java
  src/main/java/com/example/earthtalk/domain/report/dto/request/SearchReportRequest.java
  src/main/java/com/example/earthtalk/domain/report/dto/response/ReportDetailResponse.java
  src/main/java/com/example/earthtalk/domain/report/dto/response/ReportListResponse.java
  src/main/java/com/example/earthtalk/domain/report/entity/Report.java
  src/main/java/com/example/earthtalk/domain/report/entity/ReportType.java
  src/main/java/com/example/earthtalk/domain/report/entity/TargetType.java
  src/main/java/com/example/earthtalk/domain/report/service/ReportService.java
  src/main/java/com/example/earthtalk/domain/user/entity/User.java
  src/test/java/com/example/earthtalk/domain/debate/controller/ChatRoomControllerTest.java
  src/test/java/com/example/earthtalk/domain/debate/service/DebateManagementServiceTest.java
Labels: ✨feature

#25 feat: 소셜로그인 & Jwt토큰 발급 기반 인증/인가
  build.gradle
  src/main/java/com/example/earthtalk/config/SecurityConfig.java
  src/main/java/com/example/earthtalk/controller/AdminController.java
  src/main/java/com/example/earthtalk/controller/AuthController.java
  src/main/java/com/example/earthtalk/controller/NewsController.java
  src/main/java/com/example/earthtalk/controller/UserController.java
  src/main/java/com/example/earthtalk/controller/UsersController.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/OAuthAttributes.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/GoogleResourceResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/KakaoResourceResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/response/NaverResourceResponse.java
  src/main/java/com/example/earthtalk/domain/oauth/entity/RefreshToken.java
  src/main/java/com/example/earthtalk/domain/oauth/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/example/earthtalk/domain/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/example/earthtalk/domain/oauth/repository/RefreshTokenRepository.java
  src/main/java/com/example/earthtalk/domain/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/example/earthtalk/domain/user/dto/response/UserInfoResponse.java
  src/main/java/com/example/earthtalk/domain/user/entity/User.java
  src/main/java/com/example/earthtalk/domain/user/repository/UserRepository.java
  src/main/java/com/example/earthtalk/domain/user/service/UserService.java
  src/main/java/com/example/earthtalk/global/exception/ErrorCode.java
  src/main/java/com/example/earthtalk/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/earthtalk/global/exception/JwtCustomException.java
  src/main/java/com/example/earthtalk/global/exception/OAuth2AuthenticationException.java
  src/main/java/com/example/earthtalk/global/security/dto/TokenResponse.java
  src/main/java/com/example/earthtalk/global/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/example/earthtalk/global/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/earthtalk/global/security/handler/JwtAuthenticationFilter.java
  src/main/java/com/example/earthtalk/global/security/handler/JwtFilterExceptionHandler.java
  src/main/java/com/example/earthtalk/global/security/util/JwtProperties.java
  src/main/java/com/example/earthtalk/global/security/util/JwtTokenProvider.java
  src/main/resources/application.yml
  src/main/resources/static/favicon.ico
Labels: ✨feature

#30 feat: 닉네임 중복 검증 사용자 저장 구현
  build.gradle
  src/main/java/com/example/earthtalk/controller/AuthController.java
  src/main/java/com/example/earthtalk/domain/debate/controller/DebateRoomController.java
  src/main/java/com/example/earthtalk/domain/oauth/dto/OAuthAttributes.java
  src/main/java/com/example/earthtalk/domain/oauth/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/example/earthtalk/domain/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/example/earthtalk/domain/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/example/earthtalk/domain/user/dto/request/UserInfoRequest.java
  src/main/java/com/example/earthtalk/domain/user/entity/Role.java
  src/main/java/com/example/earthtalk/domain/user/entity/User.java
  src/main/java/com/example/earthtalk/domain/user/repository/UserRepository.java
  src/main/java/com/example/earthtalk/global/exception/ErrorCode.java
  src/main/java/com/example/earthtalk/global/security/dto/TokenResponse.java
  src/main/java/com/example/earthtalk/global/security/util/JwtTokenProvider.java
  src/test/java/com/example/earthtalk/domain/debate/service/DebateRoomServiceTest.java
Labels: ✨feature

#42 [refactor] FE 요구사항 칼럼 반영 및 코드 수정
  src/main/java/com/example/earthtalk/domain/debate/repository/DebateUserRepository.java
  src/main/java/com/example/earthtalk/domain/debate/service/ChatRoomService.java
  src/main/java/com/example/earthtalk/domain/report/dto/response/ReportDetailResponse.java
  src/main/java/com/example/earthtalk/domain/report/dto/response/ReportListResponse.java
  src/main/java/com/example/earthtalk/domain/report/entity/Report.java
  src/main/java/com/example/earthtalk/domain/report/service/ReportService.java
Labels: 🔨refactor

#44 Feature/#39 news fix
  src/main/java/com/example/earthtalk/controller/NewsController.java
  src/main/java/com/example/earthtalk/domain/news/dto/response/NewsDetailReponse.java
  src/main/java/com/example/earthtalk/domain/news/dto/response/NewsDetailResponse.java
  src/main/java/com/example/earthtalk/domain/news/dto/response/NewsListResponse.java
  src/main/java/com/example/earthtalk/domain/news/entity/SortType.java
  src/main/java/com/example/earthtalk/domain/news/repository/BookmarkRepository.java
  src/main/java/com/example/earthtalk/domain/news/repository/LikeRepository.java
  src/main/java/com/example/earthtalk/domain/news/service/NewsDataService.java
  src/main/java/com/example/earthtalk/global/exception/ErrorCode.java
Labels: 🔨refactor

#50 feat: 유저 프로필 수정 imageurl 업로드 기능 추가
  build.gradle
  src/main/java/com/example/earthtalk/config/S3Config.java
  src/main/java/com/example/earthtalk/controller/UserController.java
  src/main/java/com/example/earthtalk/domain/user/service/S3StorageService.java
  src/main/java/com/example/earthtalk/global/exception/ErrorCode.java
  src/main/resources/application-dev.yml
Labels: ✨feature, 🔨refactor
