Repository prgrms-web-devcourse-final-project/WEB2_3_BlockB_BE, pull requests merged in 2025-04, with the labels that each got.

#376 refactor: 소문자로 제공했던 안내 메시지를 대문자로 변경
  src/main/java/com/example/earthtalk/domain/debate/service/DebateUserService.java
Labels: 🔨refactor

#384 fix: 알림 관련 웹소켓 에러 핸들링
  src/main/java/com/example/earthtalk/global/security/handler/JwtAuthenticationFilter.java
Labels: 🐞bug

#390 fix: 웹소켓 알림 전송 확인용 로그 추가
  src/main/java/com/example/earthtalk/domain/debate/component/StompConnectInterceptor.java
  src/main/java/com/example/earthtalk/domain/notification/service/NotificationService.java
Labels: 🐞bug

#392 refactor: websocket 에 userId 저장하는 로직 변경
  src/main/java/com/example/earthtalk/domain/debate/component/CustomHandShakeHandler.java
  src/main/java/com/example/earthtalk/domain/debate/component/StompConnectInterceptor.java
  src/main/java/com/example/earthtalk/domain/debate/component/UserIdInterceptor.java
  src/main/java/com/example/earthtalk/domain/debate/config/WebSocketConfig.java
Labels: 🔨refactor

#394 refactor: 알림 웹소켓 방식 변경
  src/main/java/com/example/earthtalk/domain/debate/component/CustomHandShakeHandler.java
  src/main/java/com/example/earthtalk/domain/debate/component/NotificationSessionStore.java
  src/main/java/com/example/earthtalk/domain/debate/component/StompConnectInterceptor.java
  src/main/java/com/example/earthtalk/domain/debate/component/WebSocketEventListener.java
  src/main/java/com/example/earthtalk/domain/debate/config/WebSocketConfig.java
  src/main/java/com/example/earthtalk/domain/notification/service/NotificationService.java
Labels: 🔨refactor

#398 feat:알림 웹소켓 sessionId 받는 엔드포인트 생성
  src/main/java/com/example/earthtalk/controller/NotificationController.java
Labels: ✨feature

#400 fix: sessionId 받는 엔드포인트 코드 수정
  src/main/java/com/example/earthtalk/controller/NotificationController.java
Labels: 🐞bug

#402 fix: 알림 웹소켓 에러 핸들링
  src/main/java/com/example/earthtalk/config/SecurityConfig.java
  src/main/java/com/example/earthtalk/controller/NotificationController.java
  src/main/java/com/example/earthtalk/controller/NotificationWebSocketController.java
  src/main/java/com/example/earthtalk/domain/debate/component/StompConnectInterceptor.java
  src/main/java/com/example/earthtalk/domain/debate/component/StompPrincipal.java
  src/main/java/com/example/earthtalk/domain/debate/config/WebSocketConfig.java
Labels: 🐞bug

#404 refactor: 알림 웹소켓 전송 데이터 형식 변경
  src/main/java/com/example/earthtalk/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/example/earthtalk/domain/notification/service/NotificationService.java
Labels: 🔨refactor

#395 fix: 뉴스 리스트에서 좋아요 / 북마크 갯수가 제대로 전달되지 않던 오류를 수정
  src/main/java/com/example/earthtalk/domain/news/repository/NewsFilterRepositoryImpl.java
Labels: 🐞bug, ✨feature
